version: "3.9"
services:
  tracker:
    container_name: sq_opentracker
    image: lednerb/opentracker-docker:latest
    ports:
      - "127.0.0.1:6969:6969"
  traefik:
    image: "traefik:v2.5"
    container_name: "sq_traefik"
    command:
      - "--api.insecure=true"
      - "--providers.file=true"
      - "--providers.file.filename=/config/traefik.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/config/traefik.yml
  database:
    container_name: sq_mongodb
    image: mongo:4.4
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data:/data/db
  api:
    container_name: sq_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:44444:44444"
    volumes:
      - ./config.js:/sqtracker/config.js
    depends_on:
      - database
      - tracker
  client:
    container_name: sq_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:44445:44445"
    volumes:
      - ./config.js:/sqtracker/config.js
    depends_on:
      - api
