http:
  routers:
    api:
      service: api
      entryPoints:
        - web
      rule: "PathPrefix(`/api`, `/sq`)"
      middlewares:
        - api-prefix
        - apiHostHeaderSet
    client:
      service: client
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      middlewares:
        - clientHostHeaderSet
  services:
    api:
      loadBalancer:
        servers:
          - url: http://sq_api:3001
    client:
      loadBalancer:
        servers:
          - url: http://sq_client:3000
  middlewares:
    api-prefix:
      stripPrefix:
        prefixes:
          - /api
    clientHostHeaderSet:
      headers:
        customRequestHeaders:
          Host: "sq_client"
    apiHostHeaderSet:
      headers:
        customRequestHeaders:
          Host: "sq_api"
